// src-frontend/src/routes/popout/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { initPopoutDockview, WgpuPanel, SimplePanel } from '$lib/dockview';
  import './page.css';
  import 'dockview-core/dist/styles/dockview.css';

  let container: HTMLDivElement;

  onMount(() => {
    const handle = initPopoutDockview(container, {
      createComponent({ name }) {
        if (name === 'simple') return new SimplePanel();
        if (name === 'wgpu')   return new WgpuPanel();
        throw new Error(`Unknown component: ${name}`);
      },
    });

    return () => handle?.destroy();
  });
</script>

<svelte:head>
  <title>Panel</title>
</svelte:head>

<div bind:this={container} class="popout-root"></div>

// src-frontend/src-react/src/Popout.tsx
import { useEffect, useRef } from 'react'
import { SimplePanel, WgpuPanel } from './panels'
import { initPopoutDockview } from './dockview/dockviewPopout'
import 'dockview-core/dist/styles/dockview.css'
import './App.css'

export default function Popout() {
  const containerRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (!containerRef.current) return
    const handle = initPopoutDockview(containerRef.current, {
      createComponent({ name }) {
        switch (name) {
          case 'simple': return new SimplePanel()
          case 'wgpu': return new WgpuPanel()
          default: throw new Error(`Unknown component: ${name}`)
        }
      },
    })
    return () => { handle?.destroy() }
  }, [])

  return <div className="dock-container" style={{ height: '100vh' }} ref={containerRef} />
}
